/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Books;

import Core.LMSAlert;
import Core.ObjectParser;
import Models.Book;
import Models.SetOfBooks;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sithira
 */
public class AddBookGUI extends javax.swing.JFrame {

    private ObjectParser parser = ObjectParser.getInstance();
    
    /**
     * Creates new form AddBookGUI
     */
    public AddBookGUI() {
      
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_header = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        lbl_author = new javax.swing.JLabel();
        lbl_isbn = new javax.swing.JLabel();
        lbl_accession = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        isbn = new javax.swing.JTextField();
        accession = new javax.swing.JTextField();
        btn_add_book = new javax.swing.JButton();
        add_books_icon = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_header.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lbl_header.setForeground(new java.awt.Color(255, 51, 51));
        lbl_header.setText("ADD NEW BOOKS");
        jPanel1.add(lbl_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 230, -1));

        lbl_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 51, 51));
        lbl_title.setText("Title :");
        jPanel1.add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 70, 20));

        lbl_author.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_author.setForeground(new java.awt.Color(255, 51, 51));
        lbl_author.setText("Author : ");
        jPanel1.add(lbl_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 80, 20));

        lbl_isbn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_isbn.setForeground(new java.awt.Color(255, 51, 51));
        lbl_isbn.setText("BOOK ID :");
        jPanel1.add(lbl_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, 20));

        lbl_accession.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_accession.setForeground(new java.awt.Color(255, 51, 51));
        lbl_accession.setText("Accession : ");
        jPanel1.add(lbl_accession, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 100, 20));

        title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 250, 30));

        author.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 250, 30));

        isbn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnActionPerformed(evt);
            }
        });
        jPanel1.add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 250, 30));

        accession.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(accession, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 30));

        btn_add_book.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_add_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/add.png"))); // NOI18N
        btn_add_book.setText("Add Book");
        btn_add_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_bookActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, 40));

        add_books_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/images/add-book.png"))); // NOI18N
        jPanel1.add(add_books_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/no.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 40, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/240_F_304488952_rwBKayYk2cXgxcHQ.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_bookActionPerformed
        
        if (title.getText().isEmpty() || isbn.getText().isEmpty() 
                || author.getText().isEmpty() || accession.getText().isEmpty())
        {
            LMSAlert.showDialog("Fields cannot be empty");                      
        }
        else
        {
            Book book = new Book(isbn.getText(), title.getText(), author.getText(), Integer.parseInt(accession.getText()));
            
            try
            {
                
                SetOfBooks sob = (SetOfBooks) parser.readObject(SetOfBooks.TABLE_PATH);
                
                sob.addBook(book);
                
                parser.writeObject(SetOfBooks.TABLE_PATH, sob);               
                
                LMSAlert.showDialog("Book added succesfully");
                
                (new BooksGUI()).setVisible(true);
                
                dispose();
                
            } catch (IOException ex) {
                Logger.getLogger(AddBookGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddBookGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_btn_add_bookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBookGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accession;
    private javax.swing.JLabel add_books_icon;
    private javax.swing.JTextField author;
    private javax.swing.JButton btn_add_book;
    private javax.swing.JTextField isbn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_accession;
    private javax.swing.JLabel lbl_author;
    private javax.swing.JLabel lbl_header;
    private javax.swing.JLabel lbl_isbn;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
