/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Books;

import Core.LMSAlert;
import Core.ObjectParser;
import Models.Book;
import Models.SetOfBooks;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sithira
 */
public class BooksGUI extends javax.swing.JFrame {

    private ObjectParser parser = ObjectParser.getInstance();

    String columnNames[] = {"ISBN", "Title", "Auther", "accessionNumber", "Member Name", "onLoan ?"};

    DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);

    /**
     * Creates new form BooksGUI
     */
    public BooksGUI() {
    
        initComponents();       
        
        try {
            
            SetOfBooks sob = (SetOfBooks) parser.readObject(SetOfBooks.TABLE_PATH);
            
            loadDataToTable(sob);
            
        } catch (IOException ex) {
            Logger.getLogger(BooksGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BooksGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search_group = new javax.swing.ButtonGroup();
        btn_refresh = new javax.swing.JButton();
        main_jpanel = new javax.swing.JPanel();
        books_scroll_panel = new javax.swing.JScrollPane();
        books_table = new javax.swing.JTable();
        author_search_label = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        set_author_search = new javax.swing.JRadioButton();
        set_isbn_search = new javax.swing.JRadioButton();
        set_search_acc = new javax.swing.JRadioButton();
        search_button = new javax.swing.JButton();
        search_frame_heading = new javax.swing.JLabel();
        all_books_icon = new javax.swing.JLabel();
        set_title_search = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        add_book_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        btn_refresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/loading-arrow.png"))); // NOI18N
        btn_refresh.setText("Refresh Table");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        main_jpanel.setBackground(new java.awt.Color(255, 255, 51));

        books_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        books_scroll_panel.setViewportView(books_table);

        author_search_label.setText("Search");

        search_group.add(set_author_search);
        set_author_search.setText("Search from Author Name");

        search_group.add(set_isbn_search);
        set_isbn_search.setText("Search from ISBN");

        search_group.add(set_search_acc);
        set_search_acc.setText("Search from ACC");

        search_button.setBackground(new java.awt.Color(255, 204, 51));
        search_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/search.png"))); // NOI18N
        search_button.setText("Search now");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        search_frame_heading.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        search_frame_heading.setForeground(new java.awt.Color(255, 0, 0));
        search_frame_heading.setText("Digital Books in LMS");

        all_books_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/images/books.png"))); // NOI18N

        search_group.add(set_title_search);
        set_title_search.setText("Search from Title");

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/no.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout main_jpanelLayout = new javax.swing.GroupLayout(main_jpanel);
        main_jpanel.setLayout(main_jpanelLayout);
        main_jpanelLayout.setHorizontalGroup(
            main_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_jpanelLayout.createSequentialGroup()
                .addGroup(main_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_jpanelLayout.createSequentialGroup()
                        .addGroup(main_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(main_jpanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(author_search_label)
                                .addGap(4, 4, 4)
                                .addComponent(search))
                            .addGroup(main_jpanelLayout.createSequentialGroup()
                                .addGroup(main_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(set_author_search)
                                    .addComponent(set_isbn_search))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(main_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(set_title_search)
                                    .addComponent(set_search_acc))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(main_jpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(books_scroll_panel)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_jpanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(all_books_icon)
                .addGap(18, 18, 18)
                .addGroup(main_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_jpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(main_jpanelLayout.createSequentialGroup()
                        .addComponent(search_frame_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        main_jpanelLayout.setVerticalGroup(
            main_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_jpanelLayout.createSequentialGroup()
                .addGroup(main_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_jpanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(all_books_icon))
                    .addGroup(main_jpanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(10, 10, 10)
                        .addComponent(search_frame_heading)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(main_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_jpanelLayout.createSequentialGroup()
                        .addGroup(main_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(author_search_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(main_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(set_author_search)
                            .addComponent(set_search_acc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(main_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(set_isbn_search)
                            .addComponent(set_title_search)))
                    .addComponent(search_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(books_scroll_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add_book_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add_book_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/add.png"))); // NOI18N
        add_book_btn.setText("Add Book");
        add_book_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_book_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add_book_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                .addComponent(btn_refresh)
                .addContainerGap())
            .addComponent(main_jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_book_btn)
                    .addComponent(btn_refresh))
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_book_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_book_btnActionPerformed

        (new AddBookGUI()).setVisible(true);

        dispose();

    }//GEN-LAST:event_add_book_btnActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        
        clearTable();
        
        try {
            
            SetOfBooks sob = (SetOfBooks) parser.readObject(SetOfBooks.TABLE_PATH);
            
            loadDataToTable(sob);
            
        } catch (IOException ex) {
            Logger.getLogger(BooksGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BooksGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed

        try {
            
            clearTable();

            SetOfBooks sob = (SetOfBooks) parser.readObject(SetOfBooks.TABLE_PATH);

            if (set_author_search.isSelected()) {

                sob = sob.findBookByAuthor(search.getText());

            } else if (set_isbn_search.isSelected()) {

                sob = sob.findBookFromISBN(search.getText());

            } else if (set_title_search.isSelected()) {
                
                sob = sob.findBookFromTitle(search.getText());
                
            } else if (set_search_acc.isSelected()) {
                
                try {
                    
                    Book book = sob.findBookFromAccNumber(Integer.parseInt(search.getText()));
                
                    if (book == null)
                    {
                        LMSAlert.showDialog("No Books found");

                        return;
                    }
                    else
                    {                   

                        for(Book bk : sob.getBooks())
                        {

                            if (bk.getAccessionNumber() != Integer.parseInt(search.getText()))
                            {
                                sob.removeBook(bk);
                            }

                        }

                        sob.setBooks(null);

                        ArrayList<Book> searchBookList = new ArrayList<Book>();
                        
                        searchBookList.add(book);
                        
                        sob.setBooks(searchBookList);
  
                    }

                    } catch (Exception exception)
                    {
                        //exception.printStackTrace();
                    }

            } else {
                
                LMSAlert.showDialog("You should atleat select one category");

                return;
            }

            loadDataToTable(sob);
            
        } catch (IOException ex) {
            Logger.getLogger(BooksGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BooksGUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_search_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BooksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BooksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BooksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BooksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BooksGUI().setVisible(true);
            }
        });
    }

    private void loadDataToTable(Object object) throws IOException,
            FileNotFoundException,
            ClassNotFoundException
    {

//        SetOfBooks sop = new SetOfBooks();
//
//        Object sopo = parser.readObject(SetOfBooks.TABLE_PATH);

        final SetOfBooks soped = (SetOfBooks) object;

        books_table.setModel(tableModel);

        books_table.setCellSelectionEnabled(false);

        for (Book book : soped.getBooks()) {

            String member_name = "N/A";

            if (book.getBorrower() != null) {
                member_name = book.getBorrower().getName();
            }

            Object row[] = {
                book.getISBNNumber(),
                book.getTitle(),
                book.getAuthor(),
                book.getAccessionNumber() == -999 ? "N/A" : book.getAccessionNumber(),
                member_name,
                book.isOnLoan() ? "YES" : "NO"
            };

            tableModel.addRow(row);
        }

        books_table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = books_table.rowAtPoint(evt.getPoint());
                int col = books_table.columnAtPoint(evt.getPoint());
                if (row >= 0 && col >= 0) {

                    String ISBN = books_table
                            .getValueAt(row, 0)
                            .toString();

                    SetOfBooks setOfBooks = soped.findBookFromISBN(ISBN);

                    boolean opened = false;

                    for (Book book : setOfBooks.getBooks()) {
                        (new UpdateBookGUI(book, soped)).setVisible(true);

                        opened = true;
                    }

                    if (opened) {
                        dispose();
                    }

                }
            }
        });

    }
    
    private void clearTable()
    {
        tableModel.getDataVector().removeAllElements();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_book_btn;
    private javax.swing.JLabel all_books_icon;
    private javax.swing.JLabel author_search_label;
    private javax.swing.JScrollPane books_scroll_panel;
    private javax.swing.JTable books_table;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel main_jpanel;
    private javax.swing.JTextField search;
    private javax.swing.JButton search_button;
    private javax.swing.JLabel search_frame_heading;
    private javax.swing.ButtonGroup search_group;
    private javax.swing.JRadioButton set_author_search;
    private javax.swing.JRadioButton set_isbn_search;
    private javax.swing.JRadioButton set_search_acc;
    private javax.swing.JRadioButton set_title_search;
    // End of variables declaration//GEN-END:variables
}
