/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Books;

import Core.LMSAlert;
import Core.ObjectParser;
import Models.Book;
import Models.Member;
import Models.SetOfBooks;
import Models.SetOfMembers;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author sithira
 */
public class UpdateBookGUI extends javax.swing.JFrame {

    private Book book = null;

    private SetOfMembers som = new SetOfMembers();

    private SetOfBooks sob = null;

    private ObjectParser parser;

    private static final String RM_MEMBER = "Remove Member";

    private ArrayList<Member> member_arrays = new ArrayList<Member>();

    /**
     * Creates new form UpdateBook
     */
    public UpdateBookGUI() {

        initComponents();

    }

    public UpdateBookGUI(Book b, SetOfBooks sb) {

        initComponents();

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        parser = ObjectParser.getInstance();

        for (Book bk : sb.getBooks()) {
            if (bk.getISBNNumber().equals(b.getISBNNumber())) {
                book = bk;
            }
        }

        sob = sb;

        book_name.setText(book.getTitle());

        book_isbn.setText(book.getISBNNumber());

        String mem_name = "N/A";

        String auth_name = "N/A";

        if (book.getAuthor() != null) {
            auth_name = book.getAuthor();
        }

        book_author.setText(auth_name);

        if (book.getBorrower() != null) {
            mem_name = book.getBorrower().getName();
        }

        try {

            som = (SetOfMembers) parser.readObject(SetOfMembers.TABLE_PATH);

            member_names.addItem(RM_MEMBER);

            if (som.getMembers() != null && som.getMembers().size() > 0) {

                Member memb = null;

                for (Member member : som.getMembers()) {

                    if (book.getBorrower() != null)
                    {
                        if (member.getName().equals(book.getBorrower().getName()))
                        {
                            memb = member;
                        }
                    }

                    member_arrays.add(member);
                    member_names.addItem(member.getName());

                }

                if (memb != null) {
                    member_names.setSelectedItem(memb.getName());
                }

            }

        } catch (IOException ex) {
            Logger.getLogger(UpdateBookGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdateBookGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        book_edit_label = new javax.swing.JLabel();
        book_name_label = new javax.swing.JLabel();
        book_name = new javax.swing.JLabel();
        isbn_label = new javax.swing.JLabel();
        book_isbn = new javax.swing.JLabel();
        author_label = new javax.swing.JLabel();
        book_author = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        member_label = new javax.swing.JLabel();
        member_names = new javax.swing.JComboBox<>();
        close_button = new javax.swing.JButton();
        remove_book = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        book_edit_label.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        book_edit_label.setForeground(new java.awt.Color(255, 0, 0));
        book_edit_label.setText(" BOOK VIEW");
        jPanel1.add(book_edit_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 160, -1));

        book_name_label.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        book_name_label.setForeground(new java.awt.Color(0, 0, 255));
        book_name_label.setText("Book name :");
        jPanel1.add(book_name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        book_name.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        book_name.setText("Book Name");
        jPanel1.add(book_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 143, -1));

        isbn_label.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        isbn_label.setForeground(new java.awt.Color(0, 0, 255));
        isbn_label.setText("Book ISBN :");
        jPanel1.add(isbn_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        book_isbn.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        book_isbn.setText("Book ISBN");
        jPanel1.add(book_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        author_label.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        author_label.setForeground(new java.awt.Color(0, 0, 255));
        author_label.setText("Book Author : ");
        jPanel1.add(author_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        book_author.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        book_author.setText("Book Author");
        jPanel1.add(book_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Book Accession :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel2.setText("Book Accession");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        member_label.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        member_label.setForeground(new java.awt.Color(0, 0, 255));
        member_label.setText("Borrowed Member :");
        jPanel1.add(member_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        member_names.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jPanel1.add(member_names, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 125, -1));

        close_button.setBackground(new java.awt.Color(102, 102, 102));
        close_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        close_button.setForeground(new java.awt.Color(255, 0, 51));
        close_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/no.png"))); // NOI18N
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        remove_book.setBackground(new java.awt.Color(102, 102, 102));
        remove_book.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        remove_book.setForeground(new java.awt.Color(255, 0, 51));
        remove_book.setText("Remove Book");
        remove_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_bookActionPerformed(evt);
            }
        });
        jPanel1.add(remove_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        btn_update.setBackground(new java.awt.Color(102, 102, 102));
        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 0, 51));
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        System.exit(0);
        dispose();
    }//GEN-LAST:event_close_buttonActionPerformed

    private void remove_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_bookActionPerformed

        if (book.isOnLoan()) {
            (new BooksGUI()).setVisible(true);

            LMSAlert.showDialog("This book is on a loan. You Can't Delete it.");
        } else {
            try {

                SetOfBooks sop = (SetOfBooks) parser.readObject(SetOfBooks.TABLE_PATH);

                sop.removeBook(book);

                //LMSAlert.showDialog("Book has been removed from the LMS");
                parser.writeObject(SetOfBooks.TABLE_PATH, sop);

                parser.writeObject(SetOfMembers.TABLE_PATH, som);

                setVisible(false);

                dispose();

                (new BooksGUI()).setVisible(true);

            } catch (IOException ex) {
                Logger.getLogger(UpdateBookGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(UpdateBookGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_remove_bookActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed

        try {
            int i = member_names.getSelectedIndex();

            if (i == 0) {
                book.setBorrower(null);
            } else {
                
                Member mem = member_arrays.get((i - 1));

                System.out.println("Book count : " + mem.getLoanCount());
                
                // get the member loan count/
                if (mem.getLoanCount() < 3)
                {
                    
                    // set the book borrower.
                    book.setBorrower(mem);

                    // get all the current loans that the member has.
                    SetOfBooks curMemLoans = mem.getCurrentLoans();
                    
                    // might return null if the member does not has any loans
                    if (curMemLoans == null)
                    {
                        // if so we will set a new instance
                        curMemLoans = new SetOfBooks();                       
                    }
                    
                    // and add to it.
                    curMemLoans.addBook(book);
                    
                    // save it to the database.
                    som.getMemberFromNumber(mem.getMemberNumber());
                    
                    // save the book information
                    som.getMemberFromNumber(mem.getMemberNumber()).setCurrentLoans(sob);                                   

                    LMSAlert.showDialog("Book updates successfully");
                } else {
                    LMSAlert.showDialog("This member has reached the maximum loan count");
                }               

            }
               
            parser.writeObject(SetOfMembers.TABLE_PATH, som);
                    
            parser.writeObject(SetOfBooks.TABLE_PATH, sob);   

            (new BooksGUI()).setVisible(true);

        } catch (IOException ex) {
            Logger.getLogger(UpdateBookGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateBookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateBookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateBookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateBookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateBookGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author_label;
    private javax.swing.JLabel book_author;
    private javax.swing.JLabel book_edit_label;
    private javax.swing.JLabel book_isbn;
    private javax.swing.JLabel book_name;
    private javax.swing.JLabel book_name_label;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton close_button;
    private javax.swing.JLabel isbn_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel member_label;
    private javax.swing.JComboBox<String> member_names;
    private javax.swing.JButton remove_book;
    // End of variables declaration//GEN-END:variables
}
